### ISSUE TITLE
Feature Request: Error Handling in RegAutomation

### ISSUE THREAD

**Issue by chocola-mint** [haraldwer/GDExtensionTemplate#5]
Currently, any exception that occurs in RegAutomation fails silently (at best an error message is printed to the Build output), and the batch file would go on and boot up the Godot project. This can be pretty annoying on the user's end.

At the same time, the current implementation of codegen doesn't actually do any error handling.  It would gladly try to parse a class that's using multiple inheritance when that isn't supported by `GDCLASS`, for example. It would also try its best to parse whatever comes after a `REG_FUNCTION()` regardless if it's actually a function. Sometimes this results in compilable but semantically different code, other times it results in compile errors. It'd be more reliable to catch these cases during RegAutomation and print out the causes and line number, then abort the batch file altogether so the Godot project doesn't get booted up with a buggy build.

A tentative task list would look like:
- [x] Modify `build.bat` to detect nonzero error codes from executing RegAutomation and abort accordingly
- [x] Add error handling to `Pattern` classes. Error messages should follow the format `<filename>:<line number>: <reason> `

**Comment by haraldwer** [comment]
Dealing with all possible parsing errors would require a lot of work. Instead, I suggest putting a try-catch around the Pattern.Process() functions and printing whatever file failed to get processed, as a short term solution. 
I will make an attempt at this solution.

**Comment by haraldwer** [comment]
I have now implemented the solution I suggested above. Do you think its good enough?

**Comment by chocola-mint** [comment]
Looks good to me! I'll be closing the issue for now.
