### ISSUE TITLE
GDExtension C# bindings is now made possible by Godot 4.2 Beta 1

### ISSUE THREAD

**Issue by GeorgeS2019** [haraldwer/GDExtensionTemplate#7]
Update 18th Oct 2023

Do check out this [new project,](https://github.com/godotengine/godot/pull/82331#issuecomment-1767267091) perhaps the more official way to generate the GDExtension C# Bindings

**Comment by chocola-mint** [comment]
Assuming you're talking about https://github.com/godotengine/godot-proposals/issues/7895, it seems that it will be a very long time (+1 year, maybe 2) until the C# GDExtension becomes a reality. It's way too early to say anything, and for the time being I think our efforts will be focused on making the C++ workflow less painful first.

Personally I wouldn't be opposed to the idea, though. Just, not now.

**Comment by GeorgeS2019** [comment]
@chocola-mint 
WIP with many links on GDExtension C#  bindings: https://github.com/j20001970/GDMP/tree/csharp-bindings

https://github.com/j20001970/GDMP-demo/discussions/6#discussioncomment-7008945

**Comment by GeorgeS2019** [comment]
@chocola-mint 

You already generated the  c++ registration codes from exposed codes. 

Next is simply a way to take these exposed c++ codes e.g. methods and properties exposed from `.h or .cpp` or use any availalbe automatic cpp to c# wrapper generator.

**Comment by haraldwer** [comment]
This repository is focused on improving the c++ workflow, but you can reference it if you feel that it can contribute to the C# GDExtension discussion.
